feat: Cria tela para token de redefinição de senha
ajuda-ai-ufam/frontend pull request #123
Opened 2023-05-24 16:31 UTC by NahanTrindade

# Descrição

- Cria tela para solicitação do envio de email com o token para a redefinição de senha.

# Setup

- [ ] `yarn start`

# Cenários

## 1. Cenário A**

- [ ] Acesse a tela pelo link `/reset-password` ou pelo botão na tela de login `Esqueci minha senha`
- [ ] Informe o email que deseja receber o email com o token
- [ ] Verifique se recebeu o token no email informado

## 2. Cenário B**

- [ ] Acesse a tela pelo link `/reset-password` ou pelo botão na tela de login `Esqueci minha senha`
- [ ] Informe um email que não está cadastrado
- [ ] Verifique se recebe o erro 'Este E-mail não está cadastrad.'

## 2. Cenário B**

- [ ] Acesse a tela pelo link `/reset-password` ou pelo botão na tela de login `Esqueci minha senha`
- [ ] Informe um email que já tenha solicitado o token em menos de 30 minutos
- [ ] Verifique se recebe o erro 'Você deve aguardar 30 minutos antes de solicitar o e-mail novamente.'

2023-05-24 19:40 UTC, Marcoszz requested changes

2023-05-24 20:29 UTC, nabsonp requested changes
No mobile a tela não tá responsiva:

![Captura de Tela 2023-05-24 às 14 05 05](https://github.com/ajuda-ai-ufam/frontend/assets/26875510/6fab05c6-2daa-4ad7-bad3-8a6570bf695a)

Tablet tá sem a borda, mas no figma tem:

![Captura de Tela 2023-05-24 às 14 16 44](https://github.com/ajuda-ai-ufam/frontend/assets/26875510/564efdbd-80c0-4e9f-9de5-596d4035f04c)

2023-05-24 20:29 UTC, nabsonp commented on src/screens/resetPassword/components/resetEmail/index.tsx
> +        <InputContainer>
Esse container tem que ser um form e o botão tem que ser do tipo submit. Isso permite que a o botão seja pressionado quando vc apertar enter. Do jeito que tá só dá pra prosseguir clicando no botão

2023-05-24 20:29 UTC, nabsonp commented on src/screens/resetPassword/components/resetEmail/index.tsx
> +              name={email}
Aqui não deveria ser value? Quando a pagina carrega e dá erro o e-mail é apagado.

```suggestion
              value={email}
              name="email"
```

2023-05-24 20:29 UTC, nabsonp commented on src/screens/resetPassword/components/resetEmail/index.tsx
> +            <EmailTextField
Colocar o type também ajuda no autocomplete do browser:

```suggestion
            <EmailTextField
              type="email"
```

2023-05-24 20:29 UTC, nabsonp commented on src/screens/resetPassword/components/resetEmail/index.tsx
> +            <ConfirmButton onClick={handleConfirmEmailClick}>
Coloca esse botão desabilitado quando o e-mail é inválido ou ainda não foi digitado nada

2023-05-24 20:30 UTC, nabsonp commented on src/service/requests/useResetPasswordTokenRequest/index.ts
> +      await api.post('/user/reset-password/token', { email: emailToken });
Isso vai ser na outra tela, amigo. Essa rota recebe só o e-mail mesmo porque é nela que o token vai ser gerado ainda

2023-05-27 00:02 UTC, nabsonp requested changes
Faltou a **[variação da tela de quando a o token é enviado com sucesso](https://www.figma.com/file/rtjsSZDBG51KFRigOgGo3E/Super-Monitoria---Componentes-e-Branding-v1.0?type=design&node-id=3506-8997&t=N25uZr4SjYQogU7n-0)**.

2023-05-27 00:02 UTC, nabsonp commented on src/screens/resetPasswordEmail/components/resetEmail/index.tsx
> +          <TypographySubContainer>
Qual a necessidade de dois containers aqui? Deveria ser só um

2023-05-27 00:02 UTC, nabsonp commented on src/screens/resetPasswordEmail/components/resetEmail/index.tsx
> +              de senha.
No mobile esse texto tem que pegar a tela toda, com exceção das boras de 16px da tela. Assim tá diferente do Figma:
<img width="364" alt="Captura de Tela 2023-05-26 às 20 02 12" src="https://github.com/ajuda-ai-ufam/frontend/assets/26875510/96b31aae-2b37-4296-91ac-e5621e3ebdb9">

2023-05-27 23:48 UTC, nabsonp reviewed
Faz logo o rebase também pra resolver os problemas de merge que o github tá falando, amg

2023-05-27 23:48 UTC, nabsonp commented on src/components/registerHeader/styles.ts
> +    margin: 16px 40px 0 40px !important;
Aqui é pra ser assim:

```suggestion
    margin: 16px 16px 0 16px !important;
```

No celular tá ficando muito espaçado nas laterais do jeito que tá:
<img width="366" alt="Captura de Tela 2023-05-27 às 19 42 42" src="https://github.com/ajuda-ai-ufam/frontend/assets/26875510/d8d33365-9753-42dc-9cd9-0460c9c05f66">

2023-05-28 01:01 UTC, nabsonp approved these changes

2023-05-28 01:06 UTC, merged