feat: Cria tela de criar nova senha
ajuda-ai-ufam/frontend pull request #125
Opened 2023-06-06 15:53 UTC by NahanTrindade

# Descrição

- Cria a tela do fluxo de redefinição de senha responsável pela criação da nova senha

# Setup

- [ ] `yarn start`
- [ ] Solicite o token para redefinição de senha no link `/reset-password/email`

# Cenários

## 1. Cenário perfeito**

- [ ] Acesse o link recebido no email dentro de 30 minutos
- [ ] Entre com uma nova senha 
- [ ] Click salvar
- [ ] Verifique se sua senha foi redefinida

## 2. Token inválido**

- [ ] Acesse o link recebido no email depois de 30 minutos
- [ ] Verifique se a tela informa que o link está inválido

2023-06-09 17:47 UTC, nabsonp requested changes

2023-06-09 17:47 UTC, nabsonp commented on src/components/registerHeader/index.tsx
> +        <Link href={SCREENS.LOGIN}>
Por que essa mudança?

2023-06-09 17:47 UTC, nabsonp commented on src/service/requests/useResetPasswordRequest/index.ts
> +      const errorMessage = errorData?.message || 'Error desconhecido';
Correção de português:

```suggestion
      const errorMessage = errorData?.message || 'Erro desconhecido';
```

2023-06-09 17:47 UTC, nabsonp commented on src/screens/resetPassword/hooks/index.ts
> +  const navigate = useNavigate();
Sempre coloca as chamadas de hooks no início do hook para evitar problemas com o React no futuro. Bota esses dois para antes do primeiro useMemo

2023-06-09 17:47 UTC, nabsonp commented on src/screens/resetPassword/hooks/index.ts
> +  const validToken = useMemo(() => {
Sempre começa variáveis booleanas com `is` ou `has` para indicar que são booleanas:

```suggestion
  const isValidToken = useMemo(() => {
```

2023-06-09 17:47 UTC, nabsonp commented on src/screens/resetPassword/index.tsx
> +    return validToken ? (
Por que usou operador ternário aqui ao invés de fazer com IF como nos anteriores?

2023-06-09 17:47 UTC, nabsonp commented on src/screens/resetPassword/hooks/index.ts
> +  });
Tem que colocar a dependência do `queryToken` aqui

2023-06-09 17:47 UTC, nabsonp commented on src/service/requests/useResetPasswordRequest/index.ts
> +import { Axios, AxiosError } from 'axios';
Remove a dependência não utilizada `Axios` aqui

2023-06-09 17:47 UTC, nabsonp commented on src/screens/resetPassword/index.tsx
> +import { useNavigate } from 'react-router-dom';
Remove essa dependência não utilizada

2023-06-09 17:47 UTC, nabsonp commented on src/screens/resetPassword/styles.ts
> +import { Box, OutlinedInput } from '@mui/material';
Remove a dependência não utilizada `OutlinedInput`

2023-06-09 17:47 UTC, nabsonp commented on src/assets/invalid-link.json
Muda o nome para `warning-animation.json` para seguir o padrão dos demais de terminar com animation

2023-06-09 17:47 UTC, nabsonp commented on src/components/invalidLinkAnimation/index.tsx
> +const InvalidLinkAnimation = () => {
Coloca o nome desse componente como `WarningAnimation` para ficar mais genérico e podermos reutilizar ele em outras telas no futuro.

2023-06-09 19:06 UTC, nabsonp commented on src/components/registerHeader/index.tsx
> +        <Link href={SCREENS.LOGIN}>
ve os outros lugares que ele é usado, porque eles também vão sofrer impacto

2023-06-09 19:10 UTC, NahanTrindade commented on src/components/registerHeader/index.tsx
> +        <Link href={SCREENS.LOGIN}>
Ele é usado só nessa tela, eu criei um componente pra isso porque achei que seria reaproveitado nas duas telas de recuperação de senha, mas esse header na tela de criação de nova senha é diferente. Acho que seria melhor até remover ele daí e por direto no `/resetPasswordEmail`, não ?

2023-06-10 14:52 UTC, nabsonp approved these changes

2023-06-11 15:05 UTC, nabsonp approved these changes

2023-06-11 15:40 UTC, merged