feat: Adiciona assunto na modal de agendamento
ajuda-ai-ufam/frontend pull request #129
Opened 2023-06-21 21:06 UTC by Marcoszz

# Descrição

- Adiciona o campo de assunto na modal de agendamento

# Setup

- [ ] yarn start

# Cenários

## 1. Assunto no campo da modal

- [ ] **Antes de tudo, certifique-se que o ambiente de backend que voce esta utilizando tenha um monitor com horarios disponiveis em alguma disciplina**
- [ ] Inicie a aplicacao e faca login como **aluno**
- [ ] Na area de disciplinas, clique no botao de agendar para abrir a modal de agendamentos
- [ ] Preencha com as informacoes de professor, monitor, horario
- [ ] Primeiramente, insira um assunto que nao exista dentro do seu ambiente e complete o agendamento. Verifique se o agendamento e o assunto foram criados corretamente
- [ ] Em seguida, insira um assunto ja existente dentro do seu ambiente e complete o agendamento. Verifique se o agendamento foi criado corretamente
- [ ] Por fim, nao insira nenhum assunto e complete o agendamento. Verifique se o agendamento foi criado corretamente.
- [ ] Para todos os casos, verifique se a responsividade atende aos padroes propostos no Figma.

2023-06-22 00:34 UTC, nabsonp requested changes
Alguns problemas funcionais:
- [ ] Quando clico no botão para adicionar um novo tópico é feita mais uma requisição para listar tópicos. Essa req é desnecessária, não é?
- [ ] Quando seleciono um tópico da lista também é feito mais um GET. Ele também é desnecessário, certo?
- [ ] Se eu escrevo algo no tópico e clico fora do campo, o que eu escrevi é deletado. Isso é pra ser assim mesmo?
- [ ] Enquanto tá carregando a rota de listar tópicos tá sendo mostrada a opção de adicionar um novo e se acha um tópico com o que escrevi, some a opção de add novo e aparece o tópico que existe. O ideal é mostrar a opção de add novo quando a gente já sabe que não tem no back, então quando tá carregando não tem que aparecer nada

2023-06-22 00:34 UTC, nabsonp commented on src/components/ScheduleHelpModal/components/FormScheduleModalContent/index.tsx
> -          disabled={selectedHourIndex === -1}
Esse disabled tem que continuar e tem que ser replicado no componente do autocomplete inclusive.

2023-06-22 00:34 UTC, nabsonp commented on src/components/ScheduleHelpModal/hooks/useScheduleHelpModal.ts
> +  const handleConfirmSchedule = async () => {
Não precisa desse `async` ne? Ja que não tem `await` na função

2023-06-22 00:34 UTC, nabsonp commented on src/components/ScheduleHelpModal/hooks/useScheduleHelpModal.ts
> +    }
Esse IF pode ficar na linha 115, já que se entrar nele vc não precisar das variáveis criadas nas linhas 116 a 118.

2023-06-22 00:34 UTC, nabsonp commented on src/components/ScheduleHelpModal/hooks/useScheduleHelpModal.ts
> +    void schedule(selectedMonitorId, start, end, description, createdTopic.id);
Acho uma boa colocar isso numa função separada para não precisar duplicar esse código aqui e na função `handleConfirmSchedule`

2023-06-22 00:34 UTC, nabsonp commented on src/components/ScheduleHelpModal/hooks/useScheduleHelpModal.ts
> +    if (topicValue?.freeSolo) {
Não entendi o nome desse campo `freeSolo`. Entendi como ele tá sendo usado mas acho que podemos usar um nome mais intuitivo. O que acha de algo como `isNew` ou `isAlreadyCreated`?

2023-06-22 00:34 UTC, nabsonp commented on src/components/ScheduleHelpModal/hooks/useScheduleHelpModal.ts
> +    resetStates: resetAddTopicStates,
Você tá usando três padrões de nome aqui: `adding`, `created` e `add`. Escolhe um e segue com ele em tudo.

2023-06-22 00:34 UTC, nabsonp commented on src/components/ScheduleHelpModal/hooks/useTopics.ts
> +  const [topicValue, setTopicValue] = useState<TTopicValue | null>(null);
O que acha de `selectedTopic`? Acho que fica mais intuitivo e menos parecido com o estado `topicInputValue`. Como eles tão parecidos pode ficar confusa a diferença entre eles

2023-06-24 02:54 UTC, Marcoszz commented on src/components/ScheduleHelpModal/components/FormScheduleModalContent/index.tsx
> -          disabled={selectedHourIndex === -1}
Feito

2023-06-24 02:54 UTC, Marcoszz commented on src/components/ScheduleHelpModal/hooks/useScheduleHelpModal.ts
> +  const handleConfirmSchedule = async () => {
Feito

2023-06-24 03:04 UTC, Marcoszz commented on src/components/ScheduleHelpModal/hooks/useScheduleHelpModal.ts
> +    }
feito

2023-06-24 03:04 UTC, Marcoszz commented on src/components/ScheduleHelpModal/hooks/useScheduleHelpModal.ts
> +    void schedule(selectedMonitorId, start, end, description, createdTopic.id);
feito

2023-06-24 03:05 UTC, Marcoszz commented on src/components/ScheduleHelpModal/hooks/useScheduleHelpModal.ts
> +    if (topicValue?.freeSolo) {
Foi o nome que deram no exemplo do MUI. Vou adotar o `isNew` que faz mais sentido

2023-06-24 03:07 UTC, Marcoszz commented on src/components/ScheduleHelpModal/hooks/useScheduleHelpModal.ts
> +    resetStates: resetAddTopicStates,
usar add

2023-06-24 03:11 UTC, Marcoszz commented on src/components/ScheduleHelpModal/hooks/useTopics.ts
> +  const [topicValue, setTopicValue] = useState<TTopicValue | null>(null);
troquei pra `selectedTopicInputValue`|`selectedTopicValue`

2023-06-24 18:01 UTC, nabsonp requested changes

2023-06-24 18:01 UTC, nabsonp commented on src/components/ScheduleHelpModal/hooks/useTopics.ts
> +  const [topicValue, setTopicValue] = useState<TTopicValue | null>(null);
Acho que ainda ficou confuso porque a maior parte das letras são iguais então é difícil diferenciar. Além disso o Value no final só faz o nome ficar maior, já que ambas terminam com Value. O que acha de:
- selectedTopicInputValue -> topicInputValue
- selectedTopicValue -> selectedTopic

2023-06-24 19:37 UTC, Marcoszz commented on src/components/ScheduleHelpModal/hooks/useTopics.ts
> +  useEffect(() => {
Na realidade essa abordagem tem um problema. 

Se eu escrever qualquer coisa ou ate mesmo selecionar um valor e fechar essa modal, quando eu abrir ela denovo a lista vai vir com o resultado da ultima coisa que eu escrevi pq ela nao vai fazer uma requisicao.

2023-06-24 19:39 UTC, Marcoszz commented on src/components/ScheduleHelpModal/hooks/useTopics.ts
> +  useEffect(() => {
Alias ele nao recebe `null` tbm. Fica uma string vazia soh

2023-06-24 19:43 UTC, Marcoszz commented on src/components/ScheduleHelpModal/hooks/useTopics.ts
> +  useEffect(() => {
Na realidade a gente quer que essa req seja feita. Pq assim que o user abrir a modal a lista ja vai estar la.

2023-06-25 00:28 UTC, nabsonp approved these changes

2023-06-25 15:17 UTC, merged