feat: Cria tela de perfil
ajuda-ai-ufam/frontend pull request #142
Opened 2023-06-30 17:30 UTC by Marcoszz

# Descrição

- Cria tela de edicao de perfil

# Setup

- [ ] yarn start

# Cenários

## 1. Cenário A**

- [ ] Logue na aplicacao como aluno
- [ ] No sidebar, clique no item com o nome do aluno
- [ ] Verifique se vc foi enviado para a tela de edicao de perfil
- [ ] Verifique se a tela esta de acordo com o proposto no Figma
- [ ] Entre como coordenador e verifique os mesmos passos

**`PS: Essa PR contempla apenas a criacao da tela "Meu Perfil".`**

2023-07-03 15:36 UTC, nabsonp requested changes

2023-07-03 15:36 UTC, nabsonp commented on src/components/sidebar/hooks/useSidebar.ts
> +    ];
Quando logo com cadastro de coordenador ou professor o botão do perfil fica duplicado:

![Captura de Tela 2023-07-03 às 11 12 22](https://github.com/ajuda-ai-ufam/frontend/assets/26875510/fa240dd2-6dbf-4efd-87af-1a56756dce4a)

2023-07-03 15:36 UTC, nabsonp commented on src/screens/editProfile/components/accountBlock/index.tsx
> +const AccountBlock = ({
Seguindo o padrão mais comum de organização de um HTML seria chamar esse componente de `AccountSection`. Quando li `AccountBlock` pensei que era algo de conta bloqueada.

2023-07-03 15:36 UTC, nabsonp commented on src/screens/editProfile/components/accountBlock/index.tsx
> +      <BlockContainer>
```suggestion
      <SectionContainer>
```

2023-07-03 15:36 UTC, nabsonp commented on src/screens/editProfile/components/contactBlock/index.tsx
> +const ContactBlock = ({ contactEmailRef, linkedinRef, whatsappRef }: Props) => {
```suggestion
const ContactSection = ({ contactEmailRef, linkedinRef, whatsappRef }: Props) => {
```

2023-07-03 15:36 UTC, nabsonp commented on src/screens/editProfile/components/contactBlock/index.tsx
> +      <BlockContainer>
```suggestion
      <SectionContainer>
```

2023-07-03 15:36 UTC, nabsonp commented on src/screens/editProfile/hooks/useEditProfile.ts
> +  }, [user]);
Mais simples:

```suggestion
  const isStudent = useMemo(() => user?.type_user_id === TypeUserEnum.STUDENT, [user]);
```

2023-07-03 15:36 UTC, nabsonp commented on src/screens/editProfile/hooks/useEditProfile.ts
> +  }, []);
Mudar o título da página para `Meu Perfil`.

2023-07-03 15:36 UTC, nabsonp commented on src/screens/editProfile/hooks/useEditProfile.ts
> +  const storageRefs = () => {
Não achei esse nome intuitivo. Só entendi o que faz depois de ler o código. O que acha de `fillFormWithUserInfo` ou algo do tipo?

2023-07-03 15:36 UTC, nabsonp commented on src/screens/editProfile/hooks/useEditProfile.ts
> +    return;
Coloca um comentário com `TODO` aqui falando que a função deve ser finalizada quando fizermos a edição, por favor. Só pra não ficar com uma função perdida assim

2023-07-03 15:36 UTC, nabsonp commented on src/screens/editProfile/index.tsx
> +              <Divider />
Chris: No tablet a distância do divider pro título abaixo tá menor que no Figma.

2023-07-03 15:36 UTC, nabsonp commented on src/components/sidebar/components/SideBarItem/index.tsx
> +        {subtext ? (
Altera o componente `ItemButton` no arquivo `src/components/sidebar/components/SideBarItem/styles.ts` para que o `border-radius` seja `100px` e não `24px`, por favor. Aí vai ficar com um arredondamento mais parecido com o que tá no Figma

2023-07-03 15:36 UTC, nabsonp commented on src/screens/editProfile/index.tsx
> +const EditProfile = () => {
Em telas de PC pequenas os campos estão estourando o card:

![Captura de Tela 2023-07-03 às 11 33 10](https://github.com/ajuda-ai-ufam/frontend/assets/26875510/106ab20f-9687-4419-a194-ab7e1391c1c2)

2023-07-03 15:36 UTC, nabsonp commented on src/screens/editProfile/index.tsx
> +
Coloca um loading aqui quando estiver carregando os dados do usuário. Abrir a tela sem informações e do nada aparece ficou muito estranho. Falei pro chris colocar isso no Figma, mas vai ser um loading que nem o da tela de disciplinas e o card deve ter só o título `Meu Perfil` e o loading.

2023-07-04 01:14 UTC, Marcoszz commented on src/components/sidebar/hooks/useSidebar.ts
> +    ];
resolvidos

2023-07-04 01:21 UTC, Marcoszz commented on src/screens/editProfile/hooks/useEditProfile.ts
> +  }, [user]);
boa

2023-07-04 01:22 UTC, Marcoszz commented on src/screens/editProfile/hooks/useEditProfile.ts
> +    return;
pronto

2023-07-04 01:24 UTC, Marcoszz commented on src/screens/editProfile/hooks/useEditProfile.ts
> +  }, []);
pronto

2023-07-04 01:25 UTC, Marcoszz commented on src/screens/editProfile/hooks/useEditProfile.ts
> +  const storageRefs = () => {
coloquei `fillFormInputsWithUserInfo` que eh mais literal

2023-07-04 01:36 UTC, Marcoszz commented on src/components/sidebar/components/SideBarItem/index.tsx
> +        {subtext ? (
feito

2023-07-04 01:40 UTC, Marcoszz commented on src/screens/editProfile/index.tsx
> +const EditProfile = () => {
resolvido

2023-07-04 01:48 UTC, Marcoszz commented on src/screens/editProfile/index.tsx
> +
feito

2023-07-04 01:49 UTC, Marcoszz commented on src/screens/editProfile/index.tsx
> +              <Divider />
quanto eh a distancia? n consigo ver no figma

2023-07-04 15:03 UTC, Marcoszz commented on src/screens/editProfile/index.tsx
> +              <Divider />
resolvido

2023-07-04 15:19 UTC, nabsonp requested changes

2023-07-04 15:19 UTC, nabsonp commented on src/screens/editProfile/components/contactBlock/index.tsx
> +            <Typography variant="subtitle1">Likedin</Typography>
```suggestion
            <Typography variant="subtitle1">LinkedIn</Typography>
```

2023-07-04 15:19 UTC, nabsonp commented on src/screens/editProfile/components/accountBlock/index.tsx
> +                <Typography variant="subtitle1">Matricula</Typography>
```suggestion
                <Typography variant="subtitle1">Matrícula</Typography>
```

2023-07-04 15:19 UTC, nabsonp commented on src/screens/editProfile/components/accountBlock/index.tsx
> +                <Typography variant="subtitle1">Sobre voce</Typography>
```suggestion
                <Typography variant="subtitle1">Sobre você</Typography>
```

2023-07-04 15:27 UTC, nabsonp approved these changes

2023-07-04 15:31 UTC, merged