feat: Cria tela de edição de monitoria
ajuda-ai-ufam/frontend pull request #168
Opened 2023-08-13 03:52 UTC by NahanTrindade

# Descrição

- Cria tela de edição de monitoria, o modo de edição e o de exibição das informações
- Cria o botão de edição de monitoria na sidebar do monitor

# Setup

- [ ] `yarn start`

# Cenários

## Testar sidebar de monitor**

- [ ] Acessar conta de monitor
- [ ] Verificar se o botão `Editar Monitoria` aparece na sidebar

## Testar sidebar de não monitor**

- [ ] Acessar conta de monitor
- [ ] Verificar se o botão `Editar Monitoria` aparece na sidebar

2023-08-13 14:32 UTC, nabsonp requested changes

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +  }, [monitor]);
Simplificando:

```suggestion
  const hasAvailability = useMemo(() => !!monitor?.availability.length, [monitor]);
```

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +  }, [monitor]);
Simplificando:

```suggestion
  const hasPreference = useMemo(() => !!monitor?.monitorSettings, [monitor]);
```

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +  }, [availabilities, preference]);
Simplificando:

```suggestion
  const disableButton = useMemo(() => !availabilities || !preference, [availabilities, preference]);
```

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +    return;
Não precisa desse return

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +    return;
Não precisa desse return

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +    return;
Não precisa desse return

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +  const handleEditButtonClick = () => {
Quando o botão de editar é pressionado, a tela de edição tem que ser mostrada com os dados atuais do monitor. Do jeito que tá o campo de local e os horários já cadastrados somem e vira uma tela de cadastro e não edição

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +      setEditMode(!editMode);
Remove o query param da URL aqui tb

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +      void getMonitor(4);
Esse 4 devia ser `Number(user?.monitor?.id)`

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/index.tsx
> +                </HintContainer>
O MUI já tem o componente **[Alert](https://mui.com/material-ui/react-alert/#icons)**, você não precisa fazer um.

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/index.tsx
> +                <HintContainer>
No mobile ficou grudado:

<img width="274" alt="Captura de Tela 2023-08-13 às 10 27 48" src="https://github.com/ajuda-ai-ufam/frontend/assets/26875510/da7ced1d-4e77-4c23-87cf-1136c6d9f822">

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/components/availability/availability.tsx
> +    </AvailabilityContainer>
Como esse componente não edita só a disponibilidade, mas sim a tela inteira, ele devia estar no componente da tela e não aqui dentro

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/components/availability/availability.tsx
> +          <CancelButton disable={disableButton} onClick={handleCancelClick}>
Esse botão tá colado na parte de baixo da tela no mobile:

<img width="347" alt="Captura de Tela 2023-08-13 às 10 28 32" src="https://github.com/ajuda-ai-ufam/frontend/assets/26875510/777f42d4-3b35-4563-bba4-fff1c5a50e5c">

2023-08-13 14:32 UTC, nabsonp commented on src/screens/editMonitoring/index.tsx
> +      <Container>
O espaçamento para a beira da tela no mobile tá grande, é pra ser 16px:
<img width="338" alt="Captura de Tela 2023-08-13 às 10 32 27" src="https://github.com/ajuda-ai-ufam/frontend/assets/26875510/15fbc9cb-f438-4479-863f-5e0c0a288f16">

2023-08-13 14:50 UTC, NahanTrindade commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +      });
Eu tentei fazer só usando a constante, mas por algum motivo que eu não consegui  entender na hora o valor da constante tava sendo mudada. Quando eu dava o `setWeekDayAvailability(WEEK_DAY_AVAILABILITY_INITIAL_STATE)` ou até mesmo um `console.log(WEEK_DAY_AVAILABILITY_INITIAL_STATE)` ele retornava com os valores modificados e não os originais

2023-08-15 16:19 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +      });
Faz com o map mesmo então

2023-08-17 22:27 UTC, nabsonp requested changes

2023-08-17 22:27 UTC, nabsonp commented on src/screens/editMonitoring/hooks/types.ts
> +export const WEEK_DAY_AVAILABILITY_INITIAL_STATE: TWeekDayAvailabilityState[] =
Faltou deletar daqui

2023-08-17 22:27 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +    setWeekDayAvailability(resettedAvailability);
Como é uma edição encima do valor anterior, é melhor alterar passando a callback pro setWeekDayAvailability (como tava antes mas usando o  map)

2023-08-17 22:27 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +    return;
faltou resolver esse

2023-08-17 22:27 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +    return;
faltou resolver esse

2023-08-17 22:27 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +      void getMonitor(4);
faltou resolver esse

2023-08-17 22:27 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +    return;
faltou resolver esse

2023-08-17 22:27 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +      setEditMode(!editMode);
faltou resolver esse

2023-08-17 22:27 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +  const handleEditButtonClick = () => {
faltou resolver esse

2023-08-20 00:53 UTC, nabsonp requested changes

2023-08-20 00:53 UTC, nabsonp commented on src/screens/editMonitoring/components/availability/index.tsx
> +          <CancelButton disable={disableButton} onClick={handleCancelClick}>
O botão de cancelar tem que ter o próprio disable. Ele não fica desabilitado sempre junto do de salvar. Eu apertei pra editar e quando fui apertar pra cancelar as edições não podia.

2023-08-20 00:53 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +  const disableButton = useMemo(() => {
Editei só o local de agendamento e o botão de salvar continuou desabilitado

2023-08-20 00:53 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +  };
Sempre que o novo valor de um estado depender do anterior, você precisa fazer o set assim:

```suggestion
    setWeekDayAvailability((previousValue) => (
      previousValue.map((weekDay) => ({
        ...weekDay,
        isSelected: false,
        fromHourIndex: -1,
        toHourIndex: -1,
      }))
    ));
  };
```

2023-08-20 02:47 UTC, NahanTrindade commented on src/screens/editMonitoring/components/availability/index.tsx
> +          <CancelButton disable={disableButton} onClick={handleCancelClick}>
O botão de cancelar fica desativado até alguma alteração ser feita, certo ? O de salvar segue o mesmo critério, certo ?

2023-08-20 03:01 UTC, NahanTrindade commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +      setEditMode(!editMode);
Eu botei pra esconder a query da url assim que a tela abre, não era isso que tu quis dizer ?

2023-08-20 03:02 UTC, NahanTrindade commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +      void getMonitor(4);
Esse já foi resolvido

2023-08-23 02:22 UTC, nabsonp commented on src/screens/editMonitoring/components/availability/index.tsx
> +          <CancelButton disable={disableButton} onClick={handleCancelClick}>
não, amg. O usuário pode querer cancelar as alterações quando quiser, então ele sempre deve estar habilitado, com exceção de quando a requisição de alterar está em andamento

2023-08-23 23:15 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +      setEditMode(!editMode);
era pra remover só quando apertasse o botão de cancelar ou salvar mas isso já resolve

2023-08-23 23:52 UTC, nabsonp requested changes
- [x] Toogle desabilitado tá com bola branca, era pra ser cinza
- [x] Borda do hint deve ser mais arredondada
- [x] Cor do ícone do textbox tá num verde mais escuro que devia, devia ser a cor primary
- [x] Ao selecionar 23h na data de início aparece 23:59
- [x] Quando alterar a hora inicial, a hora final do mesmo dia deve ser resetada
- [x] Se não tiver alteração, o botão de salvar tem que ficar desabilitado
- [x] Se não tiver alteração, ao clicar no botão de cancelar não deve ser mostrada a modal de confirmar cancelamento
- [ ] Colocar 32px de distância do container pro bottom da tela no mobile para que os campos e botões não fiquem tão colados no fim da tela
- [ ] Se o local de atendimento estiver vazio ou nenhum dia for preenchido com horário de atendimento, o botão de salvar deve estar desabilitado

2023-08-23 23:52 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +    setIsOpenCancelModal(true);
É fácil de mostrar a modal só quando o usuário faz alguma alteração nos dados? Não faz sentido mostrar a confirmação de cancelamento se ele nem alterou nada.

2023-08-23 23:52 UTC, nabsonp commented on src/screens/editMonitoring/hooks/useEditMonitoring.ts
> +      setWeekDayAvailability(oldAvailability);
Quando a tela é aberta com `edit=true` e você não altera os horário de disponibilidade, ao tentar salvar a rota dá erro porque é enviado um array de disponibilidades vazio.

Isso acontece porque quando você carrega os dados da rota e atualiza o `weekDayAvailability` aqui, você tá passando o valor pro estado, que é o endereço da lista `WEEK_DAY_AVAILABILITY_INITIAL_STATE`. Sendo assim, o estado não é alterado e o `availabilities` enviado na rota também não é atualizado com as disponibilidades, já que o estado que o useMemo está observando não foi alterado.

Você precisa ter bastante cuidado com estados de tipo complexo por causa disso, alterar um índice de um array ou a chave de um objeto não altera o estado, porque o endereço do array/objeto não mudou. Esse é um dos motivos de eu ter falado em outro comentário sobre como atualizar o valor de um estado quando o novo valor depende do anterior.

Para resolver esse problema específico, só de fazer a desconstrução da lista já vai criar uma outra lista com endereço diferente, aí o estado vai ser atualizado e tudo vai dar certo:

```suggestion
      setWeekDayAvailability([...oldAvailability]);
```

2023-08-24 15:06 UTC, nabsonp requested changes
- [ ] Quando seleciono 23h no campo da hora de início, o campo de hora final devia mostrar a opção 23:59 mas está vazio
- [ ] Nas opções da hora final tá faltando a opção 23h
  - Acho que isso resolve o de cima
- [ ] A distância do container pra base da tela no mobile não funcionou, acabou comendo os botões do final

2023-08-25 00:05 UTC, nabsonp approved these changes

2023-08-25 03:25 UTC, merged