Fix readme
ajuda-ai-ufam/frontend pull request #189
Opened 2023-10-08 06:17 UTC by ThyagoLucas

# Descrição

- Reorganização do Readme do projeto.

2023-10-10 18:05 UTC, nabsonp requested changes

2023-10-10 18:05 UTC, nabsonp commented on README.md
> +$ npm or yarn start
Como o repositório tem um `yarn.lock`, é melhor falar pra usar o yarn aqui e não dar a opção do npm

2023-10-10 18:05 UTC, nabsonp commented on README.md
> +npm or yarn build
yarn aqui tb

2023-10-10 18:05 UTC, nabsonp commented on package-lock.json
melhor não subir isso pra não ficar com dois gerenciadores. Vamo manter o yarn como padrão mesmo

2023-10-10 18:05 UTC, nabsonp commented on yarn.lock
Por que isso subiu?

2023-10-10 18:05 UTC, nabsonp commented on README.md
> +$ REACT_APP_API_BASE_URL={your_backend_path_here}
Acho legal detalhar aqui que é só o base path e que tem que terminar com `/`

2023-10-10 18:14 UTC, ThyagoLucas commented on yarn.lock
provavel que não estava no .gitignore. Vou excluir

2023-10-10 18:20 UTC, ThyagoLucas commented
Correções feitas.

2023-10-10 18:26 UTC, ThyagoLucas commented on README.md
> +$ REACT_APP_API_BASE_URL={your_backend_path_here}
Alterações realizadas

2023-10-11 13:35 UTC, nabsonp approved these changes

2023-11-21 01:50 UTC, merged