Login
ajuda-ai-ufam/frontend pull request #2
Opened 2022-11-04 16:29 UTC by Marcoszz

# Descrição

- Criaçao de componentes da aplicaçao
- Adiçao de suporte à reconhecimento de arquivos svg
- Criaçao de tela de login

# Setup

- [ ] yarn
- [ ] yarn start

# Cenários

## 1. Rodar a aplicaçao e checagem com Figma

- [ ] Execute a aplicaçao com yarn start
- [ ] Verifique se o design segue o proposto [aqui](https://www.figma.com/file/rtjsSZDBG51KFRigOgGo3E/Super-Monitoria---Componentes-e-Branding-v1.0?node-id=415%3A3)

## 2. Roteamento para área de cadastro

- [ ] Execute a aplicaçao com yarn start
- [ ] Clique no botao "Cadastre-se" e verifique se foi redirecionado para a rota de cadastro (tela com a frase Hello World)
- [ ] Volte para área de login e clique no link "Cadastre-se" e verifique se foi redirecionado para a rota de cadastro (tela com a frase Hello World)

## 3. Ajustes no lint

- [ ] Execute um yarn lint e veja se nao gera nenhum erro

2022-11-04 22:50 UTC, nabsonp requested changes

2022-11-04 22:50 UTC, nabsonp commented on src/components/button/index.tsx
> +export const ButtonSecondary = styled(MUIButton).attrs({
Você pode fazer esses dois em arquivos separados pra ficar mais organizado

2022-11-04 22:50 UTC, nabsonp commented on src/screens/login/components/FormLogin/index.tsx
> +        <Typography
Cria um componente com Styled Components pra essas estilizações não ficarem aqui

2022-11-04 22:50 UTC, nabsonp commented on src/screens/login/components/FormLogin/index.tsx
> +        <Typography
Cria um componente com Styled Components pra essas estilizações não ficarem aqui

2022-11-04 22:50 UTC, nabsonp commented on src/service/requests/login/useLoginRequest.ts
> +const useLogin = () => {
Muda o nome do hook:
```suggestion
const useLoginRequest = () => {
```

2022-11-05 03:17 UTC, Marcoszz commented on src/components/button/index.tsx
> +export const ButtonSecondary = styled(MUIButton).attrs({
Deixei só um botão e criei uma prop de color para ele. Acho que ficou melhor do que ter dois dele.

2022-11-05 03:20 UTC, Marcoszz commented on src/screens/login/components/FormLogin/index.tsx
> +        <Typography
Não sei se eu não consigo ver mas acredito que sejam os dois typographys. 

Feito!

2022-11-05 03:21 UTC, Marcoszz commented on src/screens/login/components/FormLogin/index.tsx
> +        <Typography
Não sei se eu não consigo ver mas acredito que sejam os dois typographys.

Feito!

2022-11-05 14:56 UTC, nabsonp approved these changes

2022-11-05 14:56 UTC, merged