Feat student home
ajuda-ai-ufam/frontend pull request #204
Opened 2023-12-10 13:40 UTC by ThyagoLucas

# Descrição

- Cria nova home de aluno com a distinção, segundo o figma, de aluno do tipo monitor e aluno não monitor. Atentando responsividade, como foi proposto no figma. 

# Em casos de bugfix

- Qual foi a causa do bug?
- O que foi feito para corrigi-lo?

# Setup
- [ ]  precisa rodar o backend.
- [ ] yarn start, no frontend.

# Cenários

## 1. Cenário A**
- [ ] Verificar responsividade .

## 2. Cenário B**
- [ ] Verificar navegação.

2023-12-13 01:49 UTC, nabsonp requested changes
Alguns pontos sobre a PR:
- [x] Muda o título dela para algo mais intuitivo e em português
- [x] Os cenários devem ser passo a passo de como testar o que você desenvolveu, então devia ter coisas como acessar com conta de aluno, clicar em tal botão e verificar que isso aconteceu etc.
- [x] Como não é bugfix, pode apagar a seção "Em caso de bugfix"
- [x] Coloca o link do card
- [x] No setup, não precisa rodar o backend, é só apontar para o back de stg

2023-12-13 01:49 UTC, nabsonp commented on src/screens/studentHome/components/StudentSubjectsList/index.tsx
> +            <Typography variant="body1">
A cor desse texto devia ser a secondary light

2023-12-13 01:49 UTC, nabsonp commented on src/screens/studentHome/components/StudentSubjectsList/index.tsx
> +            <Typography variant="body1">Disciplinas matriculadas</Typography>
A cor desse texto devia ser a secondary light

2023-12-13 01:49 UTC, nabsonp commented on src/screens/studentHome/components/StudentSubjectsList/index.tsx
> +      </PaginationContainer>
Nós não vamos paginar essa tela. Pode requisitar só a primeira página com um tamanho grandão tipo 20

2023-12-13 01:49 UTC, nabsonp commented on src/screens/studentHome/index.tsx
> +                )}
Melhor usar o hook [useMediaQuery](https://mui.com/material-ui/react-use-media-query/)

2023-12-13 01:49 UTC, nabsonp commented on src/screens/studentHome/index.tsx
> +              >
A largura do botão no mobile tá maior que no Figma:


| Figma | Dev |
|----|----|
| ![Captura de Tela 2023-12-12 às 21 41 04](https://github.com/ajuda-ai-ufam/frontend/assets/26875510/106824f2-5207-441c-bf9b-65c8367ae59b) | ![Captura de Tela 2023-12-12 às 21 41 28](https://github.com/ajuda-ai-ufam/frontend/assets/26875510/b2d292ef-e106-42b0-bea5-a0abe560dfbd) |

2023-12-13 01:49 UTC, nabsonp commented on src/screens/studentHome/components/StudentSubjectsList/index.tsx
> +            grafia e tente novamente.
Quando o aluno não é monitor de nada e nem tá matriculado em disciplinas, o texto devia ser "Ops! Parece que você ainda não se matriculou em nenhuma disciplina. Acessar o menu “Todas as disciplinas” e matricule-se." ([figma](https://www.figma.com/file/Mx9uUhyZCRi4lmVTmDUJbK/Novas-Fun%C3%A7%C3%B5es-%7C-Super-Monitoria?type=design&node-id=829-3192&mode=design&t=hzP4SgKT30BNn3Eb-0))

2023-12-13 01:49 UTC, nabsonp commented on src/screens/studentHome/components/StudentSubjectsList/index.tsx
> +  if (subjects.length === 0) {
Quando eu não to matriculado em nada mas sou monitor de uma disciplina, a disciplina que monitoro não aparece porque cai nesse caso de fallback. Devia mostrar a disciplina que monitor e o fallback só na lista de matriculados ([figma](https://www.figma.com/file/Mx9uUhyZCRi4lmVTmDUJbK/Novas-Fun%C3%A7%C3%B5es-%7C-Super-Monitoria?type=design&node-id=843-429&mode=design&t=hzP4SgKT30BNn3Eb-0))

2023-12-28 13:10 UTC, ThyagoLucas commented
Correções feitas

2024-01-04 18:59 UTC, NahanTrindade commented on src/screens/studentHome/components/StudentSubjectsList/index.tsx
> +  //isPhone: boolean;
Apagar esse comentário

2024-01-04 19:00 UTC, NahanTrindade commented on src/screens/studentHome/components/StudentSubjectsList/index.tsx
> +            Acessar o menu “Todas as disciplinas” e matricule-se..
A frase saiu com um ponto a mais no final

2024-01-04 19:04 UTC, NahanTrindade requested changes

2024-01-04 19:04 UTC, NahanTrindade commented on src/screens/studentHome/hooks/useStudentSubjects.ts
> +  const isPhone = useMediaQuery(`(max-width:${theme.breakpoints.values.sm}px)`);
Pode trocar essa linha por `const isPhone = useMediaQuery(theme.breakpoints.down('sm'));` para ficar mais simples

2024-01-04 19:15 UTC, NahanTrindade approved these changes

2024-01-04 19:20 UTC, NahanTrindade commented on src/screens/studentHome/components/StudentSubjectsList/index.tsx
> +import { CircularProgress, Pagination, Typography } from '@mui/material';
Apaga esse Pagination aqui que foi declarado, mas não é usado

2024-01-05 04:17 UTC, ThyagoLucas commented
Novas correções feitas

2024-01-08 11:48 UTC, NahanTrindade approved these changes

2024-01-09 17:36 UTC, merged