feat: Adiciona cadastro de professor
ajuda-ai-ufam/frontend pull request #28
Opened 2022-12-01 18:09 UTC by NahanTrindade

# Descrição

- Criação da tela de cadastro do professor

# Setup

- [ ] yarn start

# Cenários

## 1. Verificação dos campos**

- [ ] Entre na área de cadastre-se e selecione a opção de "Sou Professor"
- [ ] Verifique se todos os campos obrigatórios são requisitados no formulário
- [ ] Verifique se todos os campos seguem as regras de negócios estabelecidas
- [ ] Nome Completo
- [ ] E-mail Icomp
- [ ] Senha
- [ ] Confirmação de senha

## 2. Crie um usuário**

- [ ] Entre na área de cadastre-se e selecione a opção de "Sou Professor"
- [ ] Preencha todos os campos obrigatórios corretamente
- [ ] Clique em finalizar e veja se o usuário foi cadastrado corretamente

## 3. Crie um usuário errado**
- [ ] Entre na área de cadastre-se e selecione a opção de "Sou Professor"
- [ ] Preencha todos os campos obrigatórios corretamente
- [ ] No email, coloque um email que já foi cadastrado anteriormente

2022-12-01 23:44 UTC, nabsonp requested changes

2022-12-01 23:44 UTC, nabsonp commented on src/screens/registerProfessor/components/FormRegister/styles.ts
> +  color: theme.palette.secondary.main,
Sempre usa o variant nos textos, assim a gente mantem o padrão no sistema inteiro.

2022-12-01 23:44 UTC, nabsonp commented on src/screens/registerProfessor/components/FormRegister/styles.ts
> +  color: theme.palette.secondary.main,
Se não me engano, a cor sempre é essa por padrão, então não precisa dessa linha.

2022-12-01 23:44 UTC, nabsonp commented on src/screens/registerProfessor/components/FormRegister/styles.ts
> +`;
Vale revisar com o design esses espaçamentos, porque lá ele tá usando `px` como unidade base e não `em`. Acho que vai ficar diferente.

2022-12-01 23:44 UTC, nabsonp commented on src/screens/registerProfessor/components/FormRegister/styles.ts
> +export const TypographyRegister = styledMUI(Typography)({
Sempre usa o `styled-components` para estilizar os typography. Aqui eu achei entranho que não funcionou o estilo. No form não tá um h3 no título:
<img width="647" alt="Captura de Tela 2022-12-01 às 19 39 01" src="https://user-images.githubusercontent.com/26875510/205181848-13eb5346-d375-4c55-9948-5aac9cbb30b5.png">

2022-12-01 23:44 UTC, nabsonp commented on src/screens/registerProfessor/components/FormRegister/index.tsx
> +            />
Faltou o botão para tornar senha visível.

2022-12-01 23:44 UTC, nabsonp commented on src/screens/registerProfessor/components/FormRegister/index.tsx
> +  return (
Faltou colocar o loading quando a requisição de cadastro está sendo feita.

2022-12-01 23:44 UTC, nabsonp commented on src/screens/registerProfessor/components/FormRegister/index.tsx
> +            </CancelRegisterLink>
Isso deve ser um botão do tipo texto e não um link.

2022-12-01 23:44 UTC, nabsonp commented on src/screens/registerProfessor/components/hooks/types.ts
> +};
Faltou linha em branco no final.

2022-12-01 23:44 UTC, nabsonp commented on src/service/requests/useRegisterProfessorRequest/types.ts
> +}
Faltou linha em branco no final.

2022-12-01 23:44 UTC, nabsonp commented on src/service/requests/useRegisterProfessorRequest/types.ts
> +};
Esse não é a resposta que a rota traz.

2022-12-01 23:44 UTC, nabsonp commented on src/screens/registerProfessor/components/hooks/useRegister.ts
> +const useRegisterProfessor = () => {
o nome do arquivo deve ser igual ao nome do hook. O do arquivo tá `useRegister`.

2022-12-02 12:36 UTC, nabsonp requested changes
Na versão para tablet tá aparecendo esses vetores embaixo mas não deveria ter isso de acordo com o Figma:
<img width="387" alt="Captura de Tela 2022-12-02 às 08 33 32" src="https://user-images.githubusercontent.com/26875510/205294324-f85ad4ec-7c97-4904-8090-f3935b38bf9e.png">

2022-12-02 12:36 UTC, nabsonp commented on src/screens/registerProfessor/components/FormRegister/styles.ts
> +`;
Pelo que vi aqui na versão mobile o espaçamento parece maior do que os 16px laterais que deveria ser mesmo.

2022-12-03 00:04 UTC, NahanTrindade commented on src/screens/registerProfessor/components/FormRegister/styles.ts
> +  color: theme.palette.secondary.main,
Corrigido

2022-12-03 00:04 UTC, NahanTrindade commented on src/screens/registerProfessor/components/FormRegister/styles.ts
> +  color: theme.palette.secondary.main,
Corrigido

2022-12-03 00:05 UTC, NahanTrindade commented on src/screens/registerProfessor/components/FormRegister/styles.ts
> +export const TypographyRegister = styledMUI(Typography)({
Corrigido

2022-12-03 00:05 UTC, NahanTrindade commented on src/screens/registerProfessor/components/FormRegister/index.tsx
> +            />
Corrigido

2022-12-03 00:05 UTC, NahanTrindade commented on src/screens/registerProfessor/components/FormRegister/index.tsx
> +            </CancelRegisterLink>
Corrigido

2022-12-03 00:06 UTC, NahanTrindade commented on src/screens/registerProfessor/components/hooks/types.ts
> +};
Corrigido

2022-12-03 00:07 UTC, NahanTrindade commented on src/service/requests/useRegisterProfessorRequest/types.ts
> +}
Corrigido

2022-12-03 00:08 UTC, NahanTrindade commented on src/service/requests/useRegisterProfessorRequest/types.ts
> +};
Corrigido

2022-12-03 00:11 UTC, NahanTrindade commented on src/screens/registerProfessor/components/hooks/useRegister.ts
> +const useRegisterProfessor = () => {
Corrigido

2022-12-03 16:42 UTC, nabsonp commented on src/screens/registerProfessor/components/FormRegister/index.tsx
> +            />
Esse botão tem que tornar os dois campos de senha visíveis.

2022-12-03 16:53 UTC, nabsonp commented on src/screens/registerProfessor/components/FormRegister/styles.ts
> +export const TypographyRegister = styledMUI(Typography)({
O título funcionou mas vc ainda não tá usando o `styled-components`.

2022-12-03 16:54 UTC, nabsonp commented on src/screens/registerProfessor/components/FormRegister/styles.ts
> +`;
Agora quebrou de vez.
<img width="312" alt="Captura de Tela 2022-12-03 às 12 54 31" src="https://user-images.githubusercontent.com/26875510/205452324-ff0b7b9d-ad35-4bc4-b1e9-394725d4fcf1.png">

2022-12-08 13:37 UTC, nabsonp commented on src/screens/registerProfessor/components/FormRegister/index.tsx
> +  return (
Agora faltou só alinhar o loading, que no mobile e tablet não ficou centralizado:

| Celular  | Tablet |
| ------------- | ------------- |
| ![Captura de Tela 2022-12-08 às 09 28 20](https://user-images.githubusercontent.com/26875510/206460247-841415b4-92d2-4219-a504-e08ca91e45a9.png) | ![Captura de Tela 2022-12-08 às 09 28 41](https://user-images.githubusercontent.com/26875510/206460268-df6a1883-e4e1-4cad-844f-8b082c27d20b.png) |

2022-12-08 13:39 UTC, nabsonp commented on src/screens/registerProfessor/components/FormRegister/index.tsx
> +  return (
Outra coisa sobre o carregamento é que a altura da modal não pode diminuir, ela é fixa. Do jeito que tá quando aparece o loading ela diminui:

| Form  | Loading |
| ------------- | ------------- |
| ![Captura de Tela 2022-12-08 às 09 39 06](https://user-images.githubusercontent.com/26875510/206460651-e23b284c-b99f-4800-933a-8d110b550ac0.png) | ![Captura de Tela 2022-12-08 às 09 29 34](https://user-images.githubusercontent.com/26875510/206460665-7200f97b-96a4-41fe-b4e4-57a6db943ff1.png) |

2022-12-11 17:10 UTC, merged