feat: Cria tela de solicatações de monitoria
ajuda-ai-ufam/frontend pull request #34
Opened 2022-12-22 20:21 UTC by Marcoszz

# Descrição

- Criação da tela de solicitações de monitoria (professor/coordenador)

# Setup

- [ ] yarn
- [ ] yarn start

# Cenários

Obs: Em todos os cenários checar a responsividade da tela de acordo com o [Figma](https://www.figma.com/file/rtjsSZDBG51KFRigOgGo3E/Super-Monitoria---Componentes-e-Branding-v1.0?node-id=1653%3A8742&t=St6atH3fSZ3aUtNP-0)

## 1. Checagem da tela de solicitações

- [ ] Faça login com uma conta de coordenador
- [ ] Clique em **solicitações** no sidebar
- [ ] Verifque todas as solicitações dos monitores para as todas materias são disponibilizada
- [ ] Saia da conta e logue com uma de professor
- [ ] Clique em **solicitações** no sidebar
- [ ] Verifique se todas as solicitações daquele professor são disponibilizadas

## 2. Checagem das requisições e modais

- [ ] Faça login com uma conta de coordenador
- [ ] Clique em **solicitações** no sidebar
- [ ] Aperte em **Aceitar** qualquer uma das solicitações e verifique se a modal é aberta
- [ ] Aperte em cancelar e veja se a modal é fechada
- [ ]  Aperte em **Aceitar** qualquer uma das solicitações e verifique se a modal é aberta novamente
- [ ] Aperte em **Aceito** e verifique se o aluno é aceito corretamente (mensagem de aceite e reload do componente sem aquela solicitação)
- [ ] Aperte em **Recusar** qualquer uma das solicitações e verifique se a modal é aberta
- [ ] Aperte em cancelar e veja se a modal é fechada
- [ ] Aperte em **Recusar** qualquer uma das solicitações e verifique se a modal é aberta novamente
- [ ] Aperte em **Sim, recusar** e verifique se um snackbar de info indicando que feature ainda está pronta é mostrado 

## 3. Callbacks
- [ ] Como coordenador e professor, pesquise por um aluno ou professor que não esteja nas solicitações
- [ ] Verifique se a mensagem: "Ops, não foi encontrado nenhum monitor" é mostrada
- [ ] Saia da conta e retire todas as soliciatações de um professor X do banco
- [ ] Logue na conta desse professor X e verifique se a mensagem: "Hmm... Parece que você não tem nenhuma solicitação. Que tal convidar um aluno para a plataforma?" é mostrada
- [ ] Saia da conta e retire todas as solicitações do banco
- [ ] Logue na conta de um coordenador e verifique se a mensagem: "Hmm... Parece que você não tem nenhuma solicitação. Que tal adicionar um novo professor?" é mostrada

2022-12-22 23:45 UTC, nabsonp requested changes

2022-12-22 23:45 UTC, nabsonp commented on src/components/acceptMonitorModal/hooks/useAcceptMonitorModal.ts
> +const useAcceptMonitorModal = () => {
Essa modal não precisa vir pra pasta `/src/components`. As que eu fiz e coloquei nela foram porque eu sabia que seriam reutilizadas em outras telas. Essa modal é específica para aceitar monitor, então o ideal seria ficar dentro da pasta compoents da tela mesmo.

2022-12-22 23:45 UTC, nabsonp commented on src/components/denyMonitorModal/hooks/useDenyMonitorModal.ts
> +const useDenyMonitorModal = () => {
Aqui também devia ter sido criada na pasta `components/` da própria tela.

2022-12-22 23:45 UTC, nabsonp commented on src/screens/monitorRequests/components/MonitorsRequestListItem/index.tsx
> +              handleOpenDenyModal();
Por que você separou essas duas funções? Podia ser só uma:
```suggestion
              handleOpenDenyModal(request);
```

2022-12-22 23:45 UTC, nabsonp commented on src/screens/monitorRequests/components/MonitorsRequestListItem/index.tsx
> +              handleOpenAcceptModal();
Por que você separou essas funções? Podia ser só uma:
```suggestion
              handleOpenAcceptModal(request);
```

2022-12-22 23:45 UTC, nabsonp commented on src/service/requests/useGetAllMonitorRequests/index.tsx
> +      setData(dt);
Aqui você podia ter passado logo o data para o estado, assim não precisaria criar o memo lá no hook da tela:
```suggestion
      setData(dt.data);
```

2022-12-22 23:45 UTC, nabsonp commented on src/utils/constants.ts
> +export enum TypeStatus {
Status de que? Tem que especificar porque temos muitos status no sistema.

2022-12-22 23:45 UTC, nabsonp commented on src/utils/constants.ts
> +  PENDING = 'Aguardando aprovação do Professor',
Aqui seria melhor já colocar todos os status possíveis para facilitar quando tiver alguma ação encima de outro status.

2022-12-22 23:45 UTC, nabsonp commented on src/screens/monitorRequests/hooks/useMonitorRequests.ts
> +      showErrorSnackBar(`Erro ao carregar disciplinas. Erro: ${requestsError}`);
O copia e cola ein:
```suggestion
      showErrorSnackBar(`Erro ao carregar solicitações de monitoria. Erro: ${requestsError}`);
```

2022-12-23 00:42 UTC, Marcoszz commented on src/components/acceptMonitorModal/hooks/useAcceptMonitorModal.ts
> +const useAcceptMonitorModal = () => {
Fatos. Feito.

2022-12-23 00:42 UTC, Marcoszz commented on src/components/denyMonitorModal/hooks/useDenyMonitorModal.ts
> +const useDenyMonitorModal = () => {
Feito

2022-12-23 15:32 UTC, Marcoszz commented on src/screens/monitorRequests/components/MonitorsRequestListItem/index.tsx
> +              handleOpenDenyModal();
Feito

2022-12-23 15:38 UTC, Marcoszz commented on src/screens/monitorRequests/components/MonitorsRequestListItem/index.tsx
> +              handleOpenAcceptModal();
Feito

2022-12-23 15:44 UTC, Marcoszz commented on src/service/requests/useGetAllMonitorRequests/index.tsx
> +      setData(dt);
Mas se eu passar o data para esse estado, eu perco as informações do meta da response não? E eu preciso delas para a paginação
![Screenshot from 2022-12-23 11-43-14](https://user-images.githubusercontent.com/50144860/209362167-83e96723-904c-498b-8f30-a5a1f91593bf.png)

2022-12-23 15:45 UTC, Marcoszz commented on src/utils/constants.ts
> +export enum TypeStatus {
Troquei por TypeMonitoringSTatus. Acho que fica mais explicito mesmo. Feito

2022-12-23 15:48 UTC, Marcoszz commented on src/utils/constants.ts
> +  PENDING = 'Aguardando aprovação do Professor',
Feito

2022-12-23 15:55 UTC, Marcoszz commented on src/screens/monitorRequests/hooks/useMonitorRequests.ts
> +      showErrorSnackBar(`Erro ao carregar disciplinas. Erro: ${requestsError}`);
Ops.... :joy:. Feito

2022-12-23 17:27 UTC, nabsonp commented on src/service/requests/useGetAllMonitorRequests/index.tsx
> +      setData(dt);
ah, boa. Não tinha me tocado disso. Deixa assim mesmo então 🚀

2022-12-23 17:33 UTC, nabsonp approved these changes

2022-12-23 17:33 UTC, nabsonp commented on src/utils/constants.ts
> +  PENDING = 'Aguardando aprovação do Professor',
Esses status foram atualizados. Os novos são esses:
1. Pendente: status inicial de uma monitoria esperando aprovação do professor.
2. Aprovada: status de quando o professor responsável aceita o monitor.
3. Disponivel: status de quando o monitor já tem pelo menos um horário disponível cadastrado.
4. Nesses status o monitor já está disponível para receber agendamentos.
5. Finalizada: status de quando a monitoria chegou ao fim.
6. Rejeitada: status de quando o professor rejeita a monitoria.

2022-12-23 17:33 UTC, nabsonp commented on src/screens/monitorRequests/components/denyMonitorModal/hooks/useDenyMonitorModal.ts
> +const useDenyMonitorModal = () => {
Coloca esse hook na pasta de hooks da tela mesmo, não precisa separar.

2022-12-23 17:33 UTC, nabsonp commented on src/screens/monitorRequests/components/acceptMonitorModal/hooks/useAcceptMonitorModal.ts
> +const useAcceptMonitorModal = () => {
Coloca esse hook na pasta de hooks da tela mesmo, não precisa separar.

2022-12-23 18:19 UTC, merged