Fix Redireciona para tela de Login quando o token expira
ajuda-ai-ufam/frontend pull request #46
Opened 2023-03-03 16:10 UTC by NahanTrindade

# Descrição

Adiciona um interceptor na response da api que limpa do storage local e redireciona para tela de login quando o token expira.

# Em casos de bugfix

- Qual foi a causa do bug?
- O backend retorna erro 401 quando o token de acesso expira, porém o frontend não estava lidando com esse comportamento.
- O que foi feito para corrigi-lo?
- Adição do interceptor na api do axios.

# Setup

- [ ] Use backend de staging
- [ ] yarn start
- [ ] Faça login com qualquer tipo de conta

# Cenários

## 1. Cenário A**

- [ ] Aguarde 2 horas até o tempo de expiração do token de acesso
- [ ] Acesse as das rotas do sistema logado. Ex: '/subjects'  , '/subectcs/1' ,  '/schedules'
- [ ] Verificar que é deslogado e redirecionado para a tela de login

2023-03-04 18:22 UTC, Marcoszz approved these changes

2023-03-05 00:12 UTC, nabsonp requested changes

2023-03-05 00:12 UTC, nabsonp commented on src/service/api/index.ts
> +    }
Tentei fazer login passando senha errada e a tela ficava recarregando, o que atrapalha na experiência já que a msg de login e/ou senha errados não é mostrada. O ideal seria você só redirecionar o login se o usuário estiver em uma rota em que precisa estar logado.

2023-03-05 00:13 UTC, nabsonp commented on src/service/api/index.ts
> +    }
Uma opção é no arquivo `src/utils/screens.ts` você exportar uma lista de telas em que não precisa estar logado, daí aqui nesse interceptor vc verifica se o nome da rota não está nessa lista para pode forçar o login novamente.

2023-03-06 13:46 UTC, nabsonp approved these changes

2023-03-06 13:46 UTC, nabsonp commented on src/utils/screens.ts
> +export const NOTLOGGEDSCREENS = [
Aqui o ideal seria `NOT_LOGGED_SCREENS`.

2023-03-06 16:38 UTC, merged