feat: Tela de histórico de agendamentos
ajuda-ai-ufam/frontend pull request #47
Opened 2023-03-05 17:30 UTC by Marcoszz

# Descrição

- Cria tela de histórico de agendamentos

# Setup

- [ ] yarn
- [ ] yarn start

# Cenários

## 1. Requisição dos dados

- [ ] Popule o banco utilizado com agendamentos já confirmados
- [ ] Entre na aplicação como coordenador
- [ ] Entre na aba de histórico e verifique se os dados foram carregados corretamente
- [ ] Utilize todos os filtros de acordo com os dados no seu banco e verifique se estão funcionais
- [ ] Clique em um agendamento para ver as informações dele
- [ ] Mude a página e verifique se o comportamento bate com os seus dados
- [ ] Repita os mesmos processos como **professor**
- [ ] Verifique se os horários disponíveis são apenas de materias da qual o professor é responsável
- [ ] Cheque se a tela e seus componentes são fieis ao Figma

2023-03-06 18:57 UTC, NahanTrindade requested changes
Modal de Detalhes de Agendamento maior que o modal na representação do figma

2023-03-06 23:46 UTC, nabsonp requested changes

2023-03-06 23:46 UTC, nabsonp commented on src/service/api/index.ts
> +api.interceptors.request.use((config: InternalAxiosRequestConfig) => {
Aqui deu erro por não enctronar esse `InternalAxiosRequestConfig`. Ve no yarn.lock qual versão voce tem instalada aí.

2023-03-06 23:46 UTC, nabsonp commented on src/screens/schedulesHistoric/components/FiltersForm/index.tsx
> +            <Button
Esse botão tem que ser do tipo submit para que funcione pressionar em Enter. Do jeito que tá só pega clicando no botão.

2023-03-06 23:46 UTC, nabsonp commented on src/screens/schedulesHistoric/components/EventItem/styles.ts
> +  variant: 'subtitle1',
Isso resolve aquele problema do alinhamento:
```suggestion
  textAlign: 'center',
  variant: 'subtitle1',
```

2023-03-06 23:46 UTC, nabsonp commented on src/screens/schedulesHistoric/components/FiltersForm/index.tsx
> +            color="primary"
Chris pediu para mudar a cor aqui para o cinza que usamos no select de atribuir professor para disciplina. Ele não viu que tava diferente então é melhor manter o padrão.

2023-03-08 03:45 UTC, Marcoszz commented
> Modal de Detalhes de Agendamento maior que o modal na representação do figma

Ajustado

2023-03-08 03:48 UTC, Marcoszz commented on src/screens/schedulesHistoric/hooks/useFiltersForm.ts
> +  }, []);
Resolvido

2023-03-08 03:51 UTC, Marcoszz commented on src/service/api/index.ts
> +console.log(process.env.REACT_APP_API_BASE_URL);
Resolvido

2023-03-08 03:51 UTC, Marcoszz commented on src/service/api/index.ts
> +api.interceptors.request.use((config: InternalAxiosRequestConfig) => {
Resolvido

2023-03-08 03:55 UTC, Marcoszz commented on src/screens/schedulesHistoric/components/FiltersForm/index.tsx
> +            <Button
Feito

2023-03-08 03:57 UTC, Marcoszz commented on src/screens/schedulesHistoric/components/EventItem/styles.ts
> +  variant: 'subtitle1',
Feito

2023-03-08 04:01 UTC, Marcoszz commented on src/screens/schedulesHistoric/components/FiltersForm/index.tsx
> +            color="primary"
Feito. Eu dei uma olhada lá no componente e o Chip só não tem cor (utiliza a default do tema), então só tirei o atributo de cor desse aqui.

2023-03-08 05:02 UTC, Marcoszz commented on src/screens/schedulesHistoric/hooks/useFiltersForm.ts
> +  const [endDateFilter, setEndDateFilter] = useState<Dayjs | null>(null);
Resolvido. Amigo se puder dar uma olhada carinhosa em como eu fiz ficaria grato. Eu me esqueci aonde vc falou que tinha um exemplo então fiz como eu achava que era pra ser feito.

2023-03-08 22:19 UTC, nabsonp approved these changes

2023-03-08 22:19 UTC, nabsonp commented on src/screens/schedulesHistoric/hooks/useFiltersForm.ts
> +      responsiblesOrSubjectsFilter: filters.responsiblesOrSubjectsFilter,
Para economizar linha de código:
```suggestion
      ...filters,
      beginDateFilter: date,
```

Voce pode replicar isso para todos os handleChange's.

2023-03-09 19:23 UTC, Marcoszz commented on src/screens/schedulesHistoric/hooks/useFiltersForm.ts
> +      responsiblesOrSubjectsFilter: filters.responsiblesOrSubjectsFilter,
Feito

2023-03-09 19:25 UTC, merged