feat: Landing page
ajuda-ai-ufam/frontend pull request #73
Opened 2023-04-12 03:52 UTC by Marcoszz

# Descrição

- Cria tela Landing Page

# Em casos de bugfix

- Resolvido bug de tipagem no axios
- Apenas atualizei os pacotes e adicionei o tipo mais recente aceitado no método usado pelo axios

# Setup

- [ ] Remove node_modules e yarn.lock
- [ ] yarn
- [ ] yarn start

# Cenários

## 1. Verificação da Landing Page

- [ ] Inicie a aplicação e coloque na rota da landing page (**/about**)
- [ ] Verifique todos os componentes e se estão de acordo com o proposto no Figma
- [ ] Verifique se os botões redirecionam o usuário corretamente

2023-04-12 03:53 UTC, Marcoszz commented
PS: Precisa baixar os updates em dev antes de mergear

2023-04-12 23:49 UTC, nabsonp requested changes

2023-04-12 23:49 UTC, nabsonp commented on src/screens/landingPage/components/whoAreWe/components/collaboratorsList/index.tsx
> +          </CollaboratorsContainer>
Ao invés de acessar diretamente os índices 0 e 1 o melhor seria fazer um map na lista. Algo mais ou menos assim:
```suggestion
          {
            collaborators.map((collabs) => (
              <CollaboratorsContainer>
                {collabs.map((collaborator) => (
                  <CollaboratorsListItem
                    key={collaborator.name}
                    linkedin={collaborator.linkedin}
                    name={collaborator.name}
                    role={collaborator.role}
                    photo={collaborator.photo}
                  />
                ))}
              </CollaboratorsContainer>
            ))
          }
```

2023-04-12 23:49 UTC, nabsonp commented on src/screens/landingPage/index.tsx
> +      <OutsideContainer rescale={'130vh'} color={theme.palette.secondary.main}>
Esse 130vh tá deixando a altura desse container muito grande no mobile, daí tá com esse espação sobrando:
![Captura de Tela 2023-04-12 às 19 40 17](https://user-images.githubusercontent.com/26875510/231609141-34f25438-b7e7-4b71-a292-214eb1f606a6.png)

2023-04-12 23:49 UTC, nabsonp commented on src/screens/landingPage/index.tsx
> +      <OutsideContainer rescale={'130vh'} color={'white'}>
Esse 130vh tá deixando a altura desse container muito grande no mobile, daí tá com esse espação sobrando:
![Captura de Tela 2023-04-12 às 19 41 04](https://user-images.githubusercontent.com/26875510/231609357-fd72a87f-5584-4127-b62a-aae67503a8bf.png)

2023-04-12 23:49 UTC, nabsonp commented on src/screens/landingPage/index.tsx
> +      <OutsideContainer color={theme.palette.secondary.main}>
Esse container também tá com muito espaço sobrando no mobile encima e embaixo:
![Captura de Tela 2023-04-12 às 19 42 33](https://user-images.githubusercontent.com/26875510/231609564-9dae52d7-bc27-485a-bf1e-a8a1e78768f7.png)

2023-04-12 23:49 UTC, nabsonp commented on src/screens/landingPage/index.tsx
No tablet essas alturas também tá bem diferentes do Figma

2023-04-12 23:49 UTC, nabsonp commented on src/components/Header/index.tsx
> +import { Button } from '../button';
Import não usado gerando warning

2023-04-13 00:14 UTC, nabsonp requested changes

2023-04-13 00:14 UTC, nabsonp commented on src/components/Header/styles.ts
Tem que colocar margin-bottom pro Container, pq assim tá ficando estranho:
![Captura de Tela 2023-04-12 às 20 14 32](https://user-images.githubusercontent.com/26875510/231613200-ae7011b8-803c-42ef-9b46-b4a4925e245e.png)

2023-04-15 01:48 UTC, Marcoszz commented on src/assets/landingPageImages/Fotos de perfil/christian.png
Feito

2023-04-15 01:50 UTC, Marcoszz commented on src/assets/landingPageImages/livro.svg
feito

2023-04-15 01:50 UTC, Marcoszz commented on src/assets/landingPageImages/mãos.svg
feito

2023-04-15 01:50 UTC, Marcoszz commented on src/assets/landingPageImages/notificação.svg
feito

2023-04-15 01:52 UTC, Marcoszz commented on src/assets/animação-hero.json
feito

2023-04-15 01:58 UTC, Marcoszz commented on src/components/explanationAnimation/index.tsx
> +const ExplanationAnimation = () => {
Troquei para SchedulesRoutine

2023-04-15 02:10 UTC, Marcoszz commented on src/screens/landingPage/components/whoAreWe/components/collaboratorsList/index.tsx
> +          </CollaboratorsContainer>
feito

2023-04-15 02:16 UTC, Marcoszz commented on src/components/Header/styles.ts
resolvido

2023-04-15 02:16 UTC, Marcoszz commented on src/components/Header/index.tsx
> +import { Button } from '../button';
resolvido

2023-04-15 02:18 UTC, Marcoszz commented on src/screens/landingPage/index.tsx
fatos. da pra diminuir o tamanho delas

2023-04-15 02:23 UTC, Marcoszz commented on src/screens/landingPage/index.tsx
> +      <OutsideContainer rescale={'130vh'} color={theme.palette.secondary.main}>
@nabsonp me diz com que altura tu tá testando? pq dependendo do cell, 130 foi o minino razoavel que eu achei pra deixar mais parecido com o figma sem estragar nada. olha esse aqui por ex, é 360x760:
![Screenshot from 2023-04-14 22-22-30](https://user-images.githubusercontent.com/50144860/232178617-42dca224-7543-4aa6-9ee8-3826a9cb4247.png)

com 130vh de altura ele fica bonitinho, mas com 120 já caga oh:
![Screenshot from 2023-04-14 22-21-06](https://user-images.githubusercontent.com/50144860/232178641-63c8d79c-f7da-4b60-8fe7-269bf9c2601e.png)

2023-04-15 20:22 UTC, nabsonp approved these changes
Fiz a UI Review com o Chris e resolvemos remover os assets das laterais porque eles estavam impedindo o lançamento da tela. Vou criar um card de melhoria para colocarmos eles em outro momento.

2023-04-15 20:22 UTC, merged