feat: Tela de tipo de registro
ajuda-ai-ufam/frontend pull request #8
Opened 2022-11-09 19:10 UTC by Marcoszz

# Descrição

- Criaçao da tela de escolha do tipo de registro
- Criaçao das pastas e rotas das telas de registro professor/aluno 

# Setup

- [ ] yarn start

# Cenários

## 1. Semelhança com o design

- [ ] Rode a aplicaçao com yarn start
- [ ] Verifique se a tela, e suas respectivas variantes de acordo com a resoluçao, sao semelhantes ao proposto no [Figma](https://www.figma.com/file/rtjsSZDBG51KFRigOgGo3E/Super-Monitoria---Componentes-e-Branding-v1.0?node-id=625%3A2720)

## 2. Redirecionamento dos botoes

- [ ] Rode a aplicaçao com yarn start
- [ ] Clique em algum dos links para se cadastrar e verifique se foi redirecionado para a tela de escolha do tipo de cadastro
- [ ] Clique no botao "Faça seu login" e veja se foi redirecionado para a tela de login novamente
- [ ] Volte para tela de cadastro e clique no botao "Sou Professor". Veja se foi redirecionado para a tela de registro de professor com a mensagem "Hello World Register Professor"
- [ ] Volte para tela de cadastro e clique no botao "Sou Aluno". Veja se foi redirecionado para a tela de registro de aluno com a mensagem "Hello World Register Student"

2022-11-10 00:04 UTC, nabsonp requested changes

2022-11-10 00:04 UTC, nabsonp commented on src/screens/registerType/components/SelectRegisterType/styles.ts
> +  fontFamily: 'Inter',
Por que você redefiniu as estilizações do texto? Isso devia vir automaticamente com a atribuição do `variant: 'h5'`, de acordo com o `theme`

2022-11-10 00:04 UTC, nabsonp commented on src/screens/registerType/components/SelectRegisterType/styles.ts
> +  color: '#2D2D2C',
Por que você redefiniu as estilizações do texto? Isso devia vir automaticamente com a atribuição do variant: 'h5', de acordo com o theme

2022-11-10 00:04 UTC, nabsonp commented on src/screens/registerType/components/TypeOfRegister/index.tsx
> +      </ContainerBottom>
Isso aqui também pode ir para a `src/components/` para reutilização.

2022-11-10 00:04 UTC, nabsonp commented on src/screens/registerType/components/SelectRegisterType/index.tsx
> +            handleClickNavigate(SCREENS.CREATE_PROFESSOR);
Acho que seria melhor ter criado duas funções diferentes para cada botão mesmo, daí essa lógica ficaria no hook e o componente só teria regras de estilização mesmo.

2022-11-10 00:04 UTC, nabsonp commented on src/utils/testId.ts
> +    iAmStudent: 'register-student',
Vamo padronizar colocando o tipo de componente no final e o nome da tela no inicio?
```suggestion
    loginButton: 'register-login-button',
    iAmProfessorButton: 'register-professor-button',
    iAmStudentButton: 'register-student-button',
```

2022-11-10 01:41 UTC, Marcoszz commented on src/screens/registerType/components/LogoImage/index.tsx
> +const LogoImage = () => (
Boa. Vou aderir

2022-11-10 02:04 UTC, Marcoszz commented on src/screens/registerType/components/TypeOfRegister/index.tsx
> +      </ContainerBottom>
Feito

2022-11-10 02:04 UTC, Marcoszz commented on src/screens/registerType/components/SelectRegisterType/index.tsx
> +            handleClickNavigate(SCREENS.CREATE_PROFESSOR);
Feito

2022-11-10 02:06 UTC, Marcoszz commented on src/utils/testId.ts
> +    iAmStudent: 'register-student',
Boa, não sabia se tinha um padrão mesmo. Feito

2022-11-10 02:27 UTC, Marcoszz commented on src/screens/registerType/components/SelectRegisterType/styles.ts
> +  fontFamily: 'Inter',
Então... aparentemente elas não vieram. 
![Screenshot from 2022-11-09 22-21-11](https://user-images.githubusercontent.com/50144860/200984779-9d5d36e1-04d6-49fa-9aa7-d5d1b857e819.png)

Vi aqui e fiz a mesma coisa no login. Talvez seja porque estamos usando o Typography do '@material-ui/core/Typography' e não do @mui/material.

2022-11-10 02:42 UTC, Marcoszz commented on src/screens/registerType/components/SelectRegisterType/styles.ts
> +  fontFamily: 'Inter',
Consegui aqui '-'. Por algum motivo doido qnd eu fiz os typographys o styled não reconhecia os atributos e ai fiz essa approach com o typography core. Mas agr ele reconheceu.

2022-11-10 02:42 UTC, Marcoszz commented on src/screens/registerType/components/SelectRegisterType/styles.ts
> +  color: '#2D2D2C',
Doidissi, já ajeitei

2022-11-11 02:09 UTC, nabsonp requested changes

2022-11-11 02:09 UTC, nabsonp commented on src/screens/login/components/FormLogin/styles.ts
>  import type { TypographyProps } from '@material-ui/core';
Não é mais usado então pode deletar pra não ficar dando warning.

2022-11-11 02:09 UTC, nabsonp commented on src/screens/login/components/FormLogin/styles.ts
>  import React from 'react';
Não é mais usado então pode deletar pra não ficar dando warning.

2022-11-11 02:09 UTC, nabsonp commented on src/screens/registerType/components/SelectRegisterType/styles.ts
> +`;
Nas dimensões do iPhone 5 esses botões e o texto ficaram bugados:
![Captura de tela de 2022-11-10 22-04-33](https://user-images.githubusercontent.com/26875510/201246442-d37fbfc4-a1aa-4467-afd3-a5aaf2d51044.png)

2022-11-11 02:09 UTC, nabsonp commented on src/screens/registerType/components/TypeOfRegister/styles.ts
> +`;
A tela quebrou no iPad Pro:
![Captura de tela de 2022-11-10 22-07-01](https://user-images.githubusercontent.com/26875510/201246857-fb420b72-b6a8-4817-b188-033e79611019.png)

2022-11-12 04:03 UTC, nabsonp approved these changes

2022-11-12 04:06 UTC, merged