fix: Inclui tratamento de gênero
ajuda-ai-ufam/frontend pull request #95
Opened 2023-05-01 22:06 UTC by NahanTrindade

# Descrição

- Inclui '(a)' onde tiver um gênero.

# Setup

- [ ] `yarn start`

# Alterações realizadas: 

- Monitor:
  - Subject Detail(Legenda)
  - Modal Novo Agendamento(Placeholder)
  - Schedule Detail(Legenda - Aguardando confirmação)
  - Solicitações para monitor(Sem resultados pós filtro)
  - Histórico de agendamento(Placeholder Filtro)

- Professor:
  - Subject Detail(Legenda)
  - Subject Detail(Botão "Adicionar Professor")
  - Modal Novo Agendamento(Placeholder)
  - Solicitações para monitor(Legenda lista vazia - Visão Coordenador)
  - Subject Detail(Sem professor -  Visão do coordenador)

- Aluno:
  - Subject Detail(Placeholder Filtro de busca)
  - Sschedule Detail(Legenda - Pendente)
  - Solicitações para monitor(Legenda lista vazia - Visão professor)
  - Histórico de agendamento(Placeholder Filtro)

- Serei Ajudado:
  - Schedules (Participação)
  - Schedules (Filtro de participação)

- Coordenador 
  - Subject Detail(Sem professor -  Visão do professor ou aluno)

2023-05-02 23:59 UTC, nabsonp requested changes
Dando uma busca no repositório ainda encontrei lugares que precisam do tratamento:
- src/components/assignProfessorsModal/index.tsx
- src/components/addMonitorModal/index.tsx
- src/components/ScheduleHelpModal/components/ConfirmScheduleModalContent/index.tsx
- src/screens/registerProfessor/components/FormRegister/index.tsx
- src/screens/registerType/components/SelectRegisterType/index.tsx
- src/screens/subjects/components/SubjectsListItem/index.tsx
- src/utils/constants.ts
- src/components/addMonitorModal/hooks/useAddMonitorModal.ts
- src/components/ScheduleHelpModal/components/FormScheduleModalContent/index.tsx
- src/screens/landingPage/components/advantages/index.tsx
- src/screens/landingPage/components/improveKnowledge/index.tsx
- src/screens/landingPage/components/turnIntoMonitor/index.tsx
- src/screens/monitorRequests/components/acceptMonitorModal/index.tsx
- src/screens/monitorRequests/components/denyMonitorModal/index.tsx
- src/screens/monitorRequests/components/MonitorsRequestListItem/index.tsx
- src/screens/monitorRequests/hooks/useDenyMonitorModal.ts
- src/screens/schedules/components/CancelScheduleModalContent/index.tsx
- src/screens/subjectDetails/components/subjectHeader/index.tsx
- src/components/ScheduleConfirmationModal/components/scheduleElement.tsx
- src/screens/registerStudent/components/FinalStudentRegister/index.tsx
- src/screens/registerStudent/components/MiddleStudentRegister/index.tsx
- src/screens/registerStudent/components/StartStudentRegister/index.tsx
- src/screens/registerType/components/SelectRegisterType/index.tsx

PS.: Tem uns repetidos e pode ser que tenha mais que isso ainda.

2023-05-02 23:59 UTC, nabsonp commented on src/screens/monitorRequests/components/MonitorsRequestList/index.tsx
> +            Ops... Não foi encontrado nenhum(a) monitor(a).
encontrado(a)

2023-05-02 23:59 UTC, nabsonp commented on src/screens/subjectDetails/components/subjectHeader/index.tsx
> +          width="auto"
Por que mudou isso?

2023-05-03 03:23 UTC, NahanTrindade commented on src/screens/subjectDetails/components/subjectHeader/index.tsx
> +          width="auto"
Com o (a) esse botão ficava em 2 linhas

2023-05-04 13:00 UTC, nabsonp requested changes
Outros casos:
- Artigo na linha 29 no arquivo `src/screens/schedules/components/ConfirmedScheduleModalContent/index.tsx`
- Linhas 13 e 14 do arquivo `src/screens/schedules/components/RefusedScheduleModalContent/index.tsx`
- Linha 15 do arquivo `src/components/ScheduleHelpModal/components/ConfirmedScheduleModalContent/index.tsx`

2023-05-04 13:00 UTC, nabsonp commented on src/screens/monitorRequests/components/denyMonitorModal/index.tsx
> +              Removemos a solicitação que o aluno(a) fez para ser monitor(a)
```suggestion
              Removemos a solicitação que o(a) aluno(a) fez para ser monitor(a)
```

2023-05-04 13:00 UTC, nabsonp commented on src/screens/landingPage/components/improveKnowledge/index.tsx
> +            Encontre seu monitor(a) agora!
```suggestion
            Encontre seu(sua) monitor(a) agora!
```

2023-05-04 13:00 UTC, nabsonp commented on src/screens/landingPage/components/advantages/index.tsx
> +                receber feedback dos monitores(as).
Acho que aqui não precisa por ser plural.

2023-05-04 13:00 UTC, nabsonp commented on src/components/assignProfessorsModal/index.tsx
> +          Selecione um(a) Professor(a) para torná-lo responsável pela disciplina{' '}
```suggestion
          Selecione um(a) Professor(a) para torná-lo(a) responsável pela disciplina{' '}
```

2023-05-04 15:07 UTC, NahanTrindade commented on src/screens/monitorRequests/components/denyMonitorModal/index.tsx
> +          disciplinasrc/screens/monitorRequests/components/MonitorsRequestList/index.tsx
Mexer com ctrl c e ctrl v de madrugada com sono nunca é uma boa ideia

2023-05-04 21:43 UTC, nabsonp approved these changes

2023-05-05 14:22 UTC, merged